title: ONUG 2025 - Design-Driven Automation - Lab Guide
description: Lab guide for the ONUG 2025 Design-Driven Automation workshop
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme